DROP TABLE IF EXISTS CUSTOMERS;
DROP TABLE IF EXISTS ORDERS;

CREATE TABLE CUSTOMERS
    (
        id             int generated by default as identity primary key,
        name           varchar(50)   not null,
        surname        varchar(50)   not null,
        age            bigint        not null,
        phone_number   varchar(50),
        CHECK (Age > 0 AND Age < 100)
    );


CREATE TABLE ORDERS
    (
        id           int generated  by default as identity primary key,
        date         date           not null,
        customer_id  int            REFERENCES mysql2.customers (id),
        product_name varchar(50)    not null,
        amount       varchar(50)
    );


